version: '3'
services:

  zabbix:
    image: ezynook/zabbix:${ZBX_VERSION}
    container_name: zabbix
    restart: always
    ports:
      - "${WEBPORT}:80"
      - "${SNMPPORT}:161"
      - "${ZBXAGENT}:10050"
      - "${ZBXSERVER}:10051"
      - "${DBPORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - zabbix_config:/etc/zabbix

volumes:
  mysql_data:
  zabbix_config:
